### ISSUE TITLE
Add support for KBL2.5

### ISSUE THREAD

**Issue by beckerjohannes** [4Soft-de/kbl-model#28]
## General Troubleshooting

- [X] I have checked for similar questions / issues.
- [X] I have updated to the [latest version](https://mvnrepository.com/artifact/com.foursoft.kblmodel).

## Feature Request

Currently the KBL model only support KBL2.4SR1. It should also support KBL2.5SR1

**Comment by DManstrator** [comment]
I believe this can be closed after #83 was merged, couldn't it?
