### ISSUE TITLE
Serialization with correct NS-Prefix broken.

### ISSUE THREAD

**Issue by beckerjohannes** [4Soft-de/kbl-model#92]
## General Troubleshooting

- [X] I have checked for similar issues or PRs fixing it.
- [X] I have updated to the [latest version](https://mvnrepository.com/artifact/com.foursoft.kblmodel).

## Bug Report

I upgraded from 1.4.1 to the current version and had failed tests because marshalled XML files had `ns2:` Namespace prefixes.

In the code I used a regular XML Marschaller and not the `XmlWriter`.  Core reason is, that in version 1.4.1 the JAXB Model package contained a [package-info.java](https://github.com/4Soft-de/kbl-model/blob/a85bbaaf18a414a7a55c12e0cb768692e02f3d61/kbl24/src/main/java/com/foursoft/kblmodel/kbl24/package-info.java)

Current Versions are missing this package-info and only define the prefixes via the namesmapper in the XmlWriter. Quite possible that this applies also to VEC library.

**Comment by DManstrator** [comment]
Closed due to archiving, see the ReadMe.
